volumes:
  frames: {}

services:
  frames-init:
    image: busybox:1.36
    user: "0:0"
    command: ["sh","-lc","mkdir -p /frames && chown -R 1000:1000 /frames && chmod 775 /frames"]
    volumes: ["frames:/frames"]
    restart: "no"

  detector:
    image: ghcr.io/vlanx/truck-detection:latest
    build:
      network: host
    network_mode: host
    command:
      - "--source"
      - "rtsp://10.255.35.86/stream2"
      - "--model"
      - "yolo11n.pt"
      - "--antenna"
      - "false"
    env_file: .env
    volumes:
      - frames:/frames
    restart: unless-stopped


  frameserver:
    image: alpine:3.20
    command: >
      sh -c "apk add --no-cache darkhttpd &&
             darkhttpd /frames --port 8081 --no-listing --addr 0.0.0.0"
    volumes:
      - frames:/frames:ro
    ports:
      - "8081:8081"
    restart: unless-stopped
