apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWExEWmk1YUFlTzdNSTBuNlF3V0pjaStJRUtFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSTBNRFl5TlRBM05UUXdNMW9YRFRNMApNRFl5TXpBM05UUXdNMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4anhpRUNNdmpQQ2tQKzFBL0dTN3VHS0h3RzlUMmpKZi9TNFAKUU45cFB1dFlmZ2RvYS83T1lnUHFhcDZ2eVJnMmcwcEN5YzRCSTQySnNoc1lzNHFxeVlUbjVKUVVkWG5PU0pJdgozMmkzZWFGUkVtUVZvamJWN01HQWh6ckszSDhHSTJpQVhTY2NmWWt1ZnRJVE8yYmt5MHQ2RUxnODlOUjN4Z2xyCm11cVFsRy9hZlI3UEd2RW9hTS9kblhCVXp4TDU4bU9hMVJIN1pBbzRMN0RWcU5oSmFaNnR6ZlBPNHhIV1NLRmcKdFBxWC9EaVVrWFdwOHRtSHNaUUxvZitxR3A3WStPREI3M09qUDBnSlZHTjMrTi9NYi84NzJNSGl1eTZjVXp6KwpCMlZoV1YraWJLWnZ1L3p4WnZ3VFVRK1dNdnpxY051TmV0anllZ3Uwd2JoZ1VVZEpsd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVTJKMEJwRXBpeDY0NFZHWGt5RFRLRFl3dmNMMHdId1lEVlIwakJCZ3dGb0FVMkowQnBFcGkKeDY0NFZHWGt5RFRLRFl3dmNMMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBV3E5aGtOcFJHUVVia0dnbXBWZkxaODNuNXRvbkdmT2FOUkpsS1B0bHAzQURUWHplNElaVDY2bTBGSTNmCjlXSlA2ZEVTZ3BGK0Z1ZkRRT0YzcW5DeDlmVDhUMFAwRm1yMlI0QmRqcC84VDk3ZEFXT0x3UkEvVThOemNQOWwKSVgwdExSZGR2bTlKN1dqMHEzUXNzM3R5dk15Y0xLcVYyTkQzcWJQRWFNZTBoU01XbFJ6azFaWjFwdUgwMTVsVQpNVTB2UFhhL1RDUC9lSER0ZGsvUysrMEZyemQ1OWFNSXpYUmh1U3hHWEdzWHdiSEM2bXkxelZxWWFvdk0zcHpGCnE0a0V5T1pGYzVNakQ2VlFKbnVOUDZhUEQ5bDBwMU1EOE9vY2RLYk9mT3NQcERDNy9PNjYxbERkOWhhVnRhMmEKRnBrbWxuTzlrNzQzYThtSTd1VFRBMDgxVkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.255.32.96:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: REVsUTBnSTFqNkdPSFA2K0VHbFNMdnNZbUpZaVFqb3hlYitIaVM4NEoxTT0K